<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-ABRF4IV4" ignored="0" name="Delete Customer Test" tests="4" failures="1" timestamp="26 May 2021 16:08:46 GMT" time="1.412" errors="0">
  <testcase name="deleteCustomer" time="1.261" classname="testcases.DeleteCustomerTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testcases.DeleteCustomerTest.deleteCustomer(DeleteCustomerTest.java:36)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- deleteCustomer -->
  <testcase name="deleteCustomer" time="1.281" classname="testcases.DeleteCustomerTest"/>
  <testcase name="deleteCustomer" time="1.282" classname="testcases.DeleteCustomerTest"/>
  <testcase name="deleteCustomer" time="1.407" classname="testcases.DeleteCustomerTest"/>
</testsuite> <!-- Delete Customer Test -->
