<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
<title>TestNG Report</title>
<style type="text/css">table {margin-bottom:10px;border-collapse:collapse;empty-cells:show}th,td {border:1px solid #009;padding:.25em .5em}th {vertical-align:bottom}td {vertical-align:top}table a {font-weight:bold}.stripe td {background-color: #E6EBF9}.num {text-align:right}.passedodd td {background-color: #3F3}.passedeven td {background-color: #0A0}.skippedodd td {background-color: #DDD}.skippedeven td {background-color: #CCC}.failedodd td,.attn {background-color: #F33}.failedeven td,.stripe .attn {background-color: #D00}.stacktrace {white-space:pre;font-family:monospace}.totop {font-size:85%;text-align:center;border-bottom:2px solid #000}.invisible {display:none}</style>
</head>
<body>
<table>
<tr><th>Test</th><th># Passed</th><th># Skipped</th><th># Failed</th><th>Time (ms)</th><th>Included Groups</th><th>Excluded Groups</th></tr>
<tr><th colspan="7">API Automation Sample Framework</th></tr>
<tr><td><a href="#t0">Create Customer Test</a></td><td class="num">3</td><td class="num">0</td><td class="num attn">1</td><td class="num">3,363</td><td></td><td></td></tr>
<tr class="stripe"><td><a href="#t1">Delete Customer Test</a></td><td class="num">0</td><td class="num">0</td><td class="num attn">4</td><td class="num">1,398</td><td></td><td></td></tr>
<tr><th>Total</th><th class="num">3</th><th class="num">0</th><th class="num attn">5</th><th class="num">4,761</th><th colspan="2"></th></tr>
</table>
<table id='summary'><thead><tr><th>Class</th><th>Method</th><th>Start</th><th>Time (ms)</th></tr></thead><tbody><tr><th colspan="4">API Automation Sample Framework</th></tr></tbody><tbody id="t0"><tr><th colspan="4">Create Customer Test &#8212; failed</th></tr><tr class="failedeven"><td rowspan="1">testcases.CreateCustomerTest</td><td><a href="#m0">validateCreateCustomerAPIWithInValidSecretKey</a></td><td rowspan="1">1622057039564</td><td rowspan="1">1958</td></tr><tr><th colspan="4">Create Customer Test &#8212; passed</th></tr><tr class="passedeven"><td rowspan="3">testcases.CreateCustomerTest</td><td><a href="#m1">validateCreateCustomerAPIWithValidSecretKey</a></td><td rowspan="3">1622057041539</td><td rowspan="3">1365</td></tr><tr class="passedeven"><td><a href="#m2">validateCreateCustomerAPIWithValidSecretKey</a></td></tr><tr class="passedeven"><td><a href="#m3">validateCreateCustomerAPIWithValidSecretKey</a></td></tr></tbody>
<tbody id="t1"><tr><th colspan="4">Delete Customer Test &#8212; failed</th></tr><tr class="failedeven"><td rowspan="4">testcases.DeleteCustomerTest</td><td><a href="#m4">deleteCustomer</a></td><td rowspan="4">1622057043148</td><td rowspan="4">1351</td></tr><tr class="failedeven"><td><a href="#m5">deleteCustomer</a></td></tr><tr class="failedeven"><td><a href="#m6">deleteCustomer</a></td></tr><tr class="failedeven"><td><a href="#m7">deleteCustomer</a></td></tr></tbody>
</table>
<h2>Create Customer Test</h2><h3 id="m0">testcases.CreateCustomerTest#validateCreateCustomerAPIWithInValidSecretKey</h3><table class="result"><tr class="param"><th>Parameter #1</th></tr><tr class="param stripe"><td>{email=java@way2automation.com, name=Rahul Arora, description=Adding the Second customer in framework}</td></tr><tr><th>Exception</th></tr><tr><td><div class="stacktrace">java.lang.AssertionError: expected [200] but found [401]
	at testcases.CreateCustomerTest.validateCreateCustomerAPIWithInValidSecretKey(CreateCustomerTest.java:39)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 15 stack frames</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p>
<h3 id="m1">testcases.CreateCustomerTest#validateCreateCustomerAPIWithValidSecretKey</h3><table class="result"><tr class="param"><th>Parameter #1</th></tr><tr class="param stripe"><td>{email=def@gmail.com, name=EFGH, description=Adding the Third Customer in Framework}</td></tr></table><p class="totop"><a href="#summary">back to summary</a></p>
<h3 id="m2">testcases.CreateCustomerTest#validateCreateCustomerAPIWithValidSecretKey</h3><table class="result"><tr class="param"><th>Parameter #1</th></tr><tr class="param stripe"><td>{email=fgh@gmail.com, name=IJKL, description=Adding the forth Customer in framework}</td></tr></table><p class="totop"><a href="#summary">back to summary</a></p>
<h3 id="m3">testcases.CreateCustomerTest#validateCreateCustomerAPIWithValidSecretKey</h3><table class="result"><tr class="param"><th>Parameter #1</th></tr><tr class="param stripe"><td>{email=abc@gmail.com, name=ABCD, description=Adding the Second customer in framework}</td></tr></table><p class="totop"><a href="#summary">back to summary</a></p>
<h2>Delete Customer Test</h2><h3 id="m4">testcases.DeleteCustomerTest#deleteCustomer</h3><table class="result"><tr class="param"><th>Parameter #1</th></tr><tr class="param stripe"><td>{id=cus_JYT7Uo5CrRPPA5}</td></tr><tr><th>Exception</th></tr><tr><td><div class="stacktrace">java.lang.AssertionError: expected [true] but found [false]
	at testcases.DeleteCustomerTest.deleteCustomer(DeleteCustomerTest.java:36)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 13 stack frames</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p>
<h3 id="m5">testcases.DeleteCustomerTest#deleteCustomer</h3><table class="result"><tr class="param"><th>Parameter #1</th></tr><tr class="param stripe"><td>{id=cus_JYTCXJTxlWDbv6}</td></tr><tr><th>Exception</th></tr><tr><td><div class="stacktrace">java.lang.AssertionError: expected [true] but found [false]
	at testcases.DeleteCustomerTest.deleteCustomer(DeleteCustomerTest.java:36)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 13 stack frames</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p>
<h3 id="m6">testcases.DeleteCustomerTest#deleteCustomer</h3><table class="result"><tr class="param"><th>Parameter #1</th></tr><tr class="param stripe"><td>{id=cus_JYT75W0q60E5QE}</td></tr><tr><th>Exception</th></tr><tr><td><div class="stacktrace">java.lang.AssertionError: expected [true] but found [false]
	at testcases.DeleteCustomerTest.deleteCustomer(DeleteCustomerTest.java:36)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 13 stack frames</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p>
<h3 id="m7">testcases.DeleteCustomerTest#deleteCustomer</h3><table class="result"><tr class="param"><th>Parameter #1</th></tr><tr class="param stripe"><td>{id=cus_JYTCnsRN5X6930}</td></tr><tr><th>Exception</th></tr><tr><td><div class="stacktrace">java.lang.AssertionError: expected [true] but found [false]
	at testcases.DeleteCustomerTest.deleteCustomer(DeleteCustomerTest.java:36)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 13 stack frames</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p>
</body>
</html>
